name: AppImage
on:
  workflow_dispatch:
    inputs:
      dry:
        description: 'Dry run'
        required: true
        type: boolean
      all:
        description: 'Update all'
        required: true
        type: boolean
  schedule:
    - cron: '0 3 * * 0'

jobs:
  Update:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: pip install PyGithub

    - name: Run updater
      run: |
        ./scripts/update-appimages.py \
          --token=${{ secrets.GITHUB_TOKEN }} \
          --sha=${{ github.sha }} \
          ${{ inputs.all && '--all' || '' }} \
          ${{ inputs.dry && '--dry' || '' }}
      env:
        PYTHONPATH: ${{ github.workspace }}
